CREATE DATABASE IF NOT EXISTS Games;

USE Games;

CREATE TABLE IF NOT EXISTS jogos(
	id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    genero VARCHAR(50) NOT NULL,
    plataforma VARCHAR(20) NOT NULL
);

SELECT * FROM jogos;